# -*- coding: utf-8 -*-
"""Favourite Team Statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-rQxlLyijfUbcLFmPGplofBMfdFl7u5P
"""

# Function to collect and save statistics
def collect_stats():
    # User inputs for sport, number of stats, team name, and player name
    sport = input("Enter the sport: ")
    num_stats = int(input(f"How many match statistics do you want to store for the team: "))
    team_name = input("Enter the team name: ")
    player_name = input("Enter the player name: ")

    # Writing statistics to a text file
    with open(f"{sport}_{team_name}_{player_name}_stats.txt", "w") as file:
        file.write(f"{sport}:\n\n")
        file.write(f"Player: {player_name}\n")

        # Loop to input and write individual game statistics
        for i in range(1, num_stats + 1):
            game_stat = float(input(f"Game {i}: "))
            file.write(f"Game {i}: {game_stat}\n")

    print("Statistics recorded successfully!")


if __name__ == "__main__":
    collect_stats()

# Function to display player statistics
def display_stats():
    # User inputs for sport, team name, and player name
    sport = input("Enter the sport: ")
    team_name = input("Enter the team name: ")
    player_name = input("Enter the player name: ")

    try:
        # Reading statistics from the text file
        with open(f"{sport}_{team_name}_{player_name}_stats.txt", "r") as file:
            stats = file.read()
            print(stats)
    except FileNotFoundError:
        print("Stats not found for the specified player.")


if __name__ == "__main__":
    display_stats()